parameters:
    client_action.factory.class: Flying\Bundle\ClientActionBundle\Factory\ClientActionFactory

    client_action.action.load.class: Flying\Bundle\ClientActionBundle\ClientAction\LoadClientAction
    client_action.action.event.class: Flying\Bundle\ClientActionBundle\ClientAction\EventClientAction
    client_action.action.state.class: Flying\Bundle\ClientActionBundle\ClientAction\StateClientAction

    client_action.state.class: Flying\Bundle\ClientActionBundle\State\State
    client_action.state.initializer.class: Flying\Bundle\ClientActionBundle\EventListener\StateInitListener

    client_action.state.updater.class: Flying\Bundle\ClientActionBundle\EventListener\StateUpdateListener
    client_action.state.updater.state_request_param: _state

    client_action.state.nsmap.class: Flying\Struct\Configuration\NamespacesMap
    client_action.state.nsmap.namespaces: ~

    client_action.menu.factory_extension.class: Flying\Bundle\ClientActionBundle\Menu\Factory\ClientActionExtension
    client_action.menu.voter.class: Flying\Bundle\ClientActionBundle\Menu\Voter\ClientActionVoter

    client_action.twig.extension.class: Flying\Bundle\ClientActionBundle\Twig\ClientActionExtension

services:
    # Client actions factory
    client_action.factory:
        class: %client_action.factory.class%

    # Client action objects for various actions
    client_action.action.load:
        class: %client_action.action.load.class%
        arguments: [null, @router]
        public: false
        tags:
            - { name: client_action.action, action: load }
    client_action.action.event:
        class: %client_action.action.event.class%
        public: false
        tags:
            - { name: client_action.action, action: event }
    client_action.action.state:
        class: %client_action.action.state.class%
        public: false
        tags:
            - { name: client_action.action, action: state }

    # Current application state object. Determined and defined by @client_action.state.init_event_listener
    client_action.state:
        class: %client_action.state.class%
        synthetic: true

    client_action.state.initializer:
        class: %client_action.state.initializer.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }
    client_action.state.updater:
        class: %client_action.state.updater.class%
        arguments: [%client_action.state.updater.state_request_param%]
        tags:
            - { name: kernel.event_subscriber }
            - { name: client_action.state.subscriber }

    client_action.state.nsmap:
        class: %client_action.state.nsmap.class%
        arguments: [%client_action.state.nsmap.namespaces%]

    client_action.menu.factory_extension:
        class: %client_action.menu.factory_extension.class%
        tags:
            - { name: knp_menu.factory_extension, priority: -10 }

    client_action.menu.voter:
        class: %client_action.menu.voter.class%
        arguments: [@client_action.state]
        public: false
        tags:
            - { name: knp_menu.voter, request: true }
            - { name: client_action.state.subscriber }

    client_action.twig.extension:
        class: %client_action.twig.extension.class%
        arguments: [@client_action.factory]
        public: false
        tags:
            - { name: twig.extension }
