parameters:
    client_action.action.class: Flying\Bundle\ClientActionBundle\Struct\ClientAction
    client_action.factory.class: Flying\Bundle\ClientActionBundle\Factory\ClientActionFactory

    client_action.state.class: Flying\Bundle\ClientActionBundle\State\State
    client_action.state.initializer.class: Flying\Bundle\ClientActionBundle\EventListener\StateInitListener

    client_action.state.updater.class: Flying\Bundle\ClientActionBundle\EventListener\StateUpdateListener
    client_action.state.updater.state_request_param: _state

    client_action.state.nsmap.class: Flying\Struct\Configuration\NamespacesMap
    client_action.state.nsmap.namespaces: ~

    client_action.menu.factory_extension.class: Flying\Bundle\ClientActionBundle\Menu\Factory\ClientActionExtension
    client_action.menu.voter.class: Flying\Bundle\ClientActionBundle\Menu\Voter\ClientActionVoter

services:
    client_action.factory:
        class: %client_action.factory.class%
        arguments: [%client_action.action.class%, @?router]
    client_action.state:
        class: %client_action.state.class%
        synthetic: true
    client_action.state.initializer:
        class: %client_action.state.initializer.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }
    client_action.state.updater:
        class: %client_action.state.updater.class%
        arguments: [%client_action.state.updater.state_request_param%]
        tags:
            - { name: kernel.event_subscriber }
            - { name: client_action.state.subscriber }
    client_action.state.nsmap:
        class: %client_action.state.nsmap.class%
        arguments: [%client_action.state.nsmap.namespaces%]
    client_action.menu.factory_extension:
        class: %client_action.menu.factory_extension.class%
        tags:
            - { name: knp_menu.factory_extension }
    client_action.menu.voter:
        class: %client_action.menu.voter.class%
        arguments: [@client_action.state]
        tags:
            - { name: knp_menu.voter, request: true }
            - { name: client_action.state.subscriber }
